Update patch set 1
Patch Set 1:

This broke the test build:

gitiles $ bazel test //...
ERROR: /Users/dpursehouse/git/gitiles/lib/BUILD:5:2: no such package '@jgit_archive_library//jar': error loading package 'external': The repository named 'jgit_archive_library' could not be resolved and referenced by '//lib:jgit-archive-library'.
ERROR: Analysis of target '//lib:jgit-archive-library' failed; build aborted.
INFO: Elapsed time: 0.124s
ERROR: Couldn't start the build. Unable to run tests.

Patch-set: 1
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>