Update patch set 2
Patch Set 2: Verified-1 Code-Review-1

> Patch Set 2: Verified-1 Code-Review+2
> 
> Fails "bazel test ...":
> 
> java/com/google/gitiles/DateFormatter.java:35: warning: [ImmutableEnumChecker] enums should be immutable: 'Format' has field 'defaultFormat' of type 'java.lang.ThreadLocal<java.text.DateFormat>', the declaration of type 'java.lang.ThreadLocal<java.text.DateFormat>' is not annotated with @com.google.errorprone.annotations.Immutable
>     private final ThreadLocal<DateFormat> defaultFormat;
>                                           ^
>     (see https://errorprone.info/bugpattern/ImmutableEnumChecker)
> java/com/google/gitiles/DateFormatter.java:36: warning: [ImmutableEnumChecker] enums should be immutable: 'Format' has field 'fixedTzFormat' of type 'java.lang.ThreadLocal<java.text.DateFormat>', the declaration of type 'java.lang.ThreadLocal<java.text.DateFormat>' is not annotated with @com.google.errorprone.annotations.Immutable
>     private final ThreadLocal<DateFormat> fixedTzFormat;
>                                           ^
>     (see https://errorprone.info/bugpattern/ImmutableEnumChecker)
> java/com/google/gitiles/LogServlet.java:230: error: cannot find symbol
>       walk.setFirstParent(true);
>           ^
>   symbol:   method setFirstParent(boolean)
>   location: variable walk of type RevWalk
> Target //javatests/com/google/gitiles:servlet_tests failed to build

The setFirstParent method was introduced in [1] which was submitted on jgit's master branch but has not yet been included in any release.

[1] https://git.eclipse.org/r/#/c/52806/

Patch-set: 2
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1
Label: Code-Review=-1