Update patch set 1
Patch Set 1: Code-Review-1

> Patch Set 1: Verified-1
> 
> Dev server fails with:
> 
>  Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener
> 	at org.eclipse.jetty.server.handler.ContextHandler.<clinit>(ContextHandler.java:115)
> 	at com.google.gitiles.dev.DevServer.staticHandler(DevServer.java:159)
> 	at com.google.gitiles.dev.DevServer.handler(DevServer.java:122)
> 	at com.google.gitiles.dev.DevServer.<init>(DevServer.java:112)
> 	at com.google.gitiles.dev.Main.main(Main.java:21)
>  Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionIdListener
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 5 more
> 
> I haven't tried to track it down yet.

Is this because the servlet api is outdated? We should also update directly to 9.4.27.v20200227.

Patch-set: 1
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1