Build blame cache as own java_library
This is a first step towards properly packaging of blame cache in Gerrit
server which is needed for [1]. [1] currently (PS-44) depends on the
whole gitiles-servlet and this leads to a:

  java.lang.NoClassDefFoundError: com/google/template/soy/SoyFileSet

caused by packaging the gitiles-servlet in the Gerrit core but without
all of its dependencies.

[1] https://gerrit-review.googlesource.com/72798

Change-Id: I9326b30962c21082b3d152eb6397ddcf767d1ce3