Drop servlet API 2.5
Servlet API 2.5 is only used by the dev test servlet. Drop it
and use only 3.0.

Also switch from org.eclipse.jetty.orbit to tomcat (as used in
Gerrit). With org.eclipse.jetty.orbit the dev server fails to
start with:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener
    at org.eclipse.jetty.server.handler.ContextHandler.<clinit>(ContextHandler.java:115)
    at com.google.gitiles.dev.DevServer.staticHandler(DevServer.java:160)
    at com.google.gitiles.dev.DevServer.handler(DevServer.java:123)
    at com.google.gitiles.dev.DevServer.<init>(DevServer.java:113)
    at com.google.gitiles.dev.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionIdListener
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more

Change-Id: I43e43cad86df108e45974c7531e19fdd8917bd11