Update patch set 3
Patch Set 3: Verified-1

$ bazel test ...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 8e425fa2-c1ea-4796-a955-b9b7050d5dcd
DEBUG: Rule 'com_googlesource_gerrit_bazlets' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1569339872 -0400"
DEBUG: Call stack for the definition of repository 'com_googlesource_gerrit_bazlets' which is a git_repository (rule definition at /usr/local/google/home/jrn/.cache/bazel/_bazel_jrn/5c8c56d9dd098e0b3024015c0b8456c8/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /usr/local/google/home/jrn/src/gitiles/tools/bazlets.bzl:9:9
 - /usr/local/google/home/jrn/src/gitiles/WORKSPACE:30:1
INFO: Analyzed target //javatests/com/google/gitiles:servlet_tests (75 packages loaded, 712 targets configured).
INFO: Found 1 test target...
INFO: Deleting stale sandbox base /usr/local/google/home/jrn/.cache/bazel/_bazel_jrn/5c8c56d9dd098e0b3024015c0b8456c8/sandbox
ERROR: /usr/local/google/home/jrn/src/gitiles/java/com/google/gitiles/BUILD:36:1: Building java/com/google/gitiles/libservlet-class.jar (86 source files) failed (Exit 1)
java/com/google/gitiles/DateFormatter.java:35: warning: [ImmutableEnumChecker] enums should be immutable: 'Format' has field 'defaultFormat' of type 'java.lang.ThreadLocal<java.text.DateFormat>', the declaration of type 'java.lang.ThreadLocal<java.text.DateFormat>' is not annotated with @com.google.errorprone.annotations.Immutable
    private final ThreadLocal<DateFormat> defaultFormat;
                                          ^
    (see https://errorprone.info/bugpattern/ImmutableEnumChecker)
java/com/google/gitiles/DateFormatter.java:36: warning: [ImmutableEnumChecker] enums should be immutable: 'Format' has field 'fixedTzFormat' of type 'java.lang.ThreadLocal<java.text.DateFormat>', the declaration of type 'java.lang.ThreadLocal<java.text.DateFormat>' is not annotated with @com.google.errorprone.annotations.Immutable
    private final ThreadLocal<DateFormat> fixedTzFormat;
                                          ^
    (see https://errorprone.info/bugpattern/ImmutableEnumChecker)
java/com/google/gitiles/LogServlet.java:230: error: cannot find symbol
      walk.setFirstParent(true);
          ^
  symbol:   method setFirstParent(boolean)
  location: variable walk of type RevWalk
Target //javatests/com/google/gitiles:servlet_tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 23.982s, Critical Path: 7.84s
INFO: 33 processes: 18 remote cache hit, 12 linux-sandbox, 3 worker.
FAILED: Build did NOT complete successfully

Patch-set: 3
Reviewer: Gerrit User 1011842 <1011842@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1