Update patch set 4
Patch Set 4: Verified-1

//gitiles-servlet:servlet_tests                                          FAILED in 7.3s
There were 2 failures:
1) noteInList(com.google.gitiles.doc.DocServletTest)
java.lang.AssertionError: Not true that <"<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>index.md</title><link rel="stylesheet" type="text/css" href="/+static/base.css" /><link rel="stylesheet" type="text/css" href="/+static/doc.css" /><link rel="stylesheet" type="text/css" href="/+static/prettify/p
        at com.google.gitiles.doc.DocServletTest.noteInList(DocServletTest.java:114)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Caused by: java.lang.AssertionError: Not true that <"<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>index.md</title><link rel="stylesheet" type="text/css" href="/+static/base.css" /><link rel="stylesheet" type="text/css" href="/+static/doc.css" /><link rel="stylesheet" type="text/css" href="/+static
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
        at com.google.common.truth.Subject.failComparingToStrings(Subject.java:348)
        at com.google.common.truth.Subject.fail(Subject.java:325)
        at com.google.common.truth.StringSubject.contains(StringSubject.java:126)
        ... 34 more


2) namedAnchor(com.google.gitiles.doc.DocServletTest)
java.lang.AssertionError: Not true that <"<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Section {#debug}</title><link rel="stylesheet" type="text/css" href="/+static/base.css" /><link rel="stylesheet" type="text/css" href="/+static/doc.css" /><link rel="stylesheet" type="text/css" href="/+static/pr
        at com.google.gitiles.doc.DocServletTest.namedAnchor(DocServletTest.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Caused by: java.lang.AssertionError: Not true that <"<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Section {#debug}</title><link rel="stylesheet" type="text/css" href="/+static/base.css" /><link rel="stylesheet" type="text/css" href="/+static/doc.css" /><link rel="stylesheet" type="text/css" href="
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
        at com.google.common.truth.Subject.failComparingToStrings(Subject.java:348)
        at com.google.common.truth.Subject.fail(Subject.java:325)
        at com.google.common.truth.StringSubject.contains(StringSubject.java:126)
        ... 34 more

Patch-set: 4
Reviewer: Jonathan Nieder <1011842@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1