Update patch set 7
Patch Set 7:

> :( `buck test --all` isn't passing for me:
 > 
 > FAILURE com.google.gitiles.PathServletTest symlinkHtml: Variant
 > expression "$customVariant" doesn't evaluate to a valid type (Only
 > string and integer are supported).
 > com.google.template.soy.tofu.SoyTofuException: Variant expression
 > "$customVariant" doesn't evaluate to a valid type (Only string and
 > integer are supported).

Found it: delcall calls need explicit conversion from null to empty string if no variant is set (as in the tests).

Patch-set: 7