Add missing commons-io dependency in BUILD file
Adding //lib:commons-io to DEPS in java/com/google/gitiles/BUILD ensures
that archive generation (used by ArchiveServlet) has the required
CountingOutputStream class available at runtime.

This fixes the NoClassDefFoundError occurring when using tgz links.

Change-Id: Id7551f10385e01f6f9db6a73d1f5f877fd55c281