Update patch set 2
Patch Set 2:

> Patch Set 2: Verified-1 -Code-Review
> 
> This is causing many of the tests to fail with errors like:
> 
>  java.lang.ClassCastException: com.google.template.soy.data.SanitizedContent$SanitizedCompatString cannot be cast to com.google.template.soy.data.restricted.PrimitiveData

Do we need to update Soy?

Patch-set: 2
Reviewer: Gerrit User 1010008 <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>