Update patch set 1
Patch Set 1:

This broke tests:

 FAILURE treeText: expected null, but was:<text/plain>
 java.lang.AssertionError: expected null, but was:<text/plain>
         at org.junit.Assert.fail(Assert.java:88)
         at org.junit.Assert.failNotNull(Assert.java:664)
         at org.junit.Assert.assertNull(Assert.java:646)
         at org.junit.Assert.assertNull(Assert.java:656)
         at com.google.gitiles.PathServletTest.buildText(PathServletTest.java:288)
         at com.google.gitiles.PathServletTest.treeText(PathServletTest.java:193)

It's not Gerrit, `buck test` only takes 4s ;)

Patch-set: 1
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0