Update patch set 8
Patch Set 8:

> The approach and the amount of code in this change is appropriate,
 > this will unblock us.
 > 
 > However, it doesn't work for me:
 > 
 > $ ./tools/eclipse/project.sh
 > ...........
 > ERROR: error loading package 'tools/eclipse': Extension file not
 > found. Unable to load package for '@com_googlesource_gerrit_bazlets//tools/eclipse:project_path.bzl':

So this CL depends on pending change for bazlets repository that wasn't merged yet: [1]. My suggestion is to verify this CL in three steps:

Step 1:

* 1.1 Clone bazlets locally
* 1.2 Apply in bazlets: [1]
* 1.3 Switch to local bazlets repository in WORKSPACE by uncommenting and adjusting this line in load_bazlets() rule:

  local_path = "/home/dave/projects/bazlets"

* 1.4 Confirm that it works as expected
* 1.5 Vote VRFY+1 on: [1].

Step 2:

* 2.1 Submit: [1].

Step 3:

* 3.1 Upload a new patch set with new SHA1 for bazlets
* 3.2 Remove debugging line in load_bazlets invocation
* 3.3 Vanilla

  tools/eclipse/project.sh

should just work.

* [1] https://gerrit-review.googlesource.com/95253

Patch-set: 8